### ISSUE TITLE
Bracken-Build Update

### ISSUE THREAD

**Issue by jboconnor13** [sterrettJD/HoMi#81]
Received the following error from the build_braken rule:
 
Activating conda environment: .snakemake/conda/493b3e3d4f2f922634081f0f09ce4284_
/gpfs/alpine1/scratch/joconnor@xsede.org/HoMi/.snakemake/conda/493b3e3d4f2f922634081f0f09ce4284_/bin/bracken-build: line 231: syntax error: unexpected end of file

It appears there was a syntax error in line 231 (end of the script) due to an upstream error on line 189:
original: 
`if [ $0 -eq 0 ]`
updated: 
`fi 
if [ $? -eq 0 ] `

Update in bracken-build script can be found here: 
https://github.com/jenniferlu717/Bracken/commit/d7f63d8ff9d7d9c1bcf31d62f0ee642d6fd3d8c5

**Comment by sterrettJD** [comment]
Hey @jboconnor13 what did you end up doing to fix it? Just bumping up your Bracken version?

**Comment by jboconnor13** [comment]
This was edited manually in the bracken-build script. This is likely a pip update issue within the Bracken repo.

**Comment by sterrettJD** [comment]
Hey Jack, I'm getting this error now. I wonder if a lower version of bracken would fix it? Like 2.9 instead of 3.0? It looks like someone else is having this issue. https://github.com/jenniferlu717/Bracken/issues/285

**Comment by sterrettJD** [comment]
@jboconnor13 just commented in that other issue on bracken's github asking if they can push those fixes to conda so HoMi can have that automated... Hopefully this will be fixed soon!

**Comment by sterrettJD** [comment]
@jboconnor13 not sure if they will fix it anytime soon, doesn't seem like there are many responses on the Bracken issues lately. 

I'll try to make another issue since it should be a quick fix.

Additionally - the kraken and bracken database builds are bottleneck steps (particularly kraken), so I'm going to look into just using prebuilt indexes from here https://benlangmead.github.io/aws-indexes/k2

**Comment by sterrettJD** [comment]
Hey Jack, I think I've gotten around this by using the prebuilt kraken/bracken indexes ([prebuilt_indexes branch](https://github.com/sterrettJD/HoMi/tree/prebuilt_indexes)). On Fiji, this is downloading VERY slowly (2 days, since it's >200GB and the connection speed seems really poor). I think it'd be worthwhile to download the database using the steps shown in that rule, to the LozuponeLab petalibrary store on Alpine, so we can just share that across studies, and it's only required to download once.

**Comment by sterrettJD** [comment]
This should now be fixed as of release v1.0.11! Feel free to give it a try if you have a sec, Jack.
